# kubeadm-config.yaml
# kubeadm supports the following configuration types:

---

apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  # ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 10.0.0.106
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: k8s-master
  # taints:
  # - effect: NoSchedule
  #   key: node-role.kubernetes.io/master

---

# https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.20.0
apiServer:
  timeoutForControlPlane: 4m0s
certificatesDir: /etc/kubernetes/pki
clusterName: k8s_mgr_prod
# controllerManager: {}
controllerManager:
  extraArgs:
    cluster-signing-cert-file: /etc/kubernetes/pki/ca.crt
    cluster-signing-key-file: /etc/kubernetes/pki/ca.key
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
networking:
  dnsDomain: 
  - cluster.local
  - k8s-master.dellius.app
  serviceSubnet: 10.96.0.0/12
scheduler: {}

---

# apiVersion: kubelet.config.k8s.io/v1beta1
# kind: KubeletConfiguration
# cgroupDriver: systemd

# ---

# apiVersion: kubeproxy.config.k8s.io/v1alpha1
# kind: KubeProxyConfiguration

# ---

# apiVersion: kubeadm.k8s.io/v1beta2
# kind: JoinConfiguration