apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"type":"local"},"name":"jenkins-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"10Gi"},"claimRef":{"name":"jenkins-pvc","namespace":"jenkins"},"hostPath":{"path":"/mnt/nfs/jenkins_data"},"storageClassName":"jenkins-storage"}}
  creationTimestamp: "2021-08-14T17:01:04Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  name: jenkins-pv
  resourceVersion: "30127"
  uid: 9e155bfb-4170-47ff-a7f6-f94e9411b6a5
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-pvc
    namespace: jenkins
    resourceVersion: "30125"
    uid: 719bcf05-8fa2-4345-b14b-5388d0ceb047
  hostPath:
    path: /mnt/nfs/jenkins_data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-storage
  volumeMode: Filesystem
status:
  phase: Bound
