apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2020-11-05T19:14:38Z
  name: ingress-nginx-config
  namespace: ingress-nginx
data:
  # example of a simple property defined using --from-literal
  example.property.1: hello
  example.property.2: world
  # example of a complex property defined using --from-file
  example.property.file: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3