# https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/#deploy-mysql
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-sfs
  labels:
    app: mysql-sfs
spec: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-sfs
  namespace: mysql-sfs
  labels:
    app: mysql-sfs
spec:
  type: NodePort
  selector:
    app: mysql-sfs
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-sfs
  namespace: mysql-sfs
  labels:
    app: mysql-sfs
spec:
  selector:
    matchLabels:
      app: mysql-sfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-sfs
    spec:
      containers:
      - image: mysql:latest
        name: mysql-sfs
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: developer
        ports:
        - containerPort: 3306
          name: mysql-sfs
          protocol: TCP
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: my-conf
          mountPath: /etc/mysql
        - name: mysql-files
          mountPath: /mysql_files
        # - name: kube-api-access-ktb5n
        #   mountPath: /var/run/secrets/kubernetes.io/serviceaccount      
        #   readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 512Mi
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: k8s-master
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim-sfs
      - name: mysql-files
        persistentVolumeClaim:
          claimName: mysql-pv-claim-sfs-sql
      - name: my-conf
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: my-conf
          items:
          - key: my.cnf
            path: my.cnf
      # - name: kube-api-access-ktb5n
      #   projected:
      #     defaultMode: 420
      #     sources:
      #     - serviceAccountToken:
      #         expirationSeconds: 3607
      #         path: token
      #     - configMap:
      #         items:
      #         - key: ca.crt
      #           path: ca.crt
      #         name: kube-root-ca.crt
      #     - downwardAPI:
      #         items:
      #         - fieldRef:
      #             apiVersion: v1
      #             fieldPath: metadata.namespace
      #           path: namespace

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-sfs
  namespace: mysql-sfs
  labels:
    app: mysql-sfs
    type: local    
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql_sfs/data"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pv-claim-sfs
    namespace: mysql-sfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-sfs
  namespace: mysql-sfs
  labels:
    app: mysql-sfs
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Bind mount local files to remote cluster to be used in a PersistentVolume using rsync.
# Run the command below:
# sudo rsync -a -e "ssh -p <PORT>" ./sql/  [USER]@[HOST IP/URL]:/mnt/mysql_sfs/sql 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-sfs-sql
  namespace: mysql-sfs
  labels:
    app: mysql-sfs
    type: local    
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql_sfs/sql"
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pv-claim-sfs-sql
    namespace: mysql-sfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-sfs-sql
  namespace: mysql-sfs
  labels:
    app: mysql-sfs
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
data:
  my.cnf: |
    [mysqld]
    secure_file_priv = "/mysql_files"
kind: ConfigMap
metadata:
  name: my-conf
  namespace: mysql-sfs
  labels:
    app: mysql-sfs

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mysql-sfs
  namespace: mysql-sfs
  labels:
    app: mysql-sfs
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysql-sfs
  targetCPUUtilizationPercentage: 25
status:
  observedGeneration: 1
  currentReplicas: 1
  desiredReplicas: 1